# Autogenerated by nbdev

d = { 'settings': { 'branch': 'master',
                'doc_baseurl': '/evolutionaryDiscounting',
                'doc_host': 'https://erozon.github.io',
                'git_url': 'https://github.com/erozon/evolutionaryDiscounting',
                'lib_path': 'evolutionaryDiscounting'},
  'syms': {'evolutionaryDiscounting.core': {'evolutionaryDiscounting.core.foo': ('core.html#foo', 'evolutionaryDiscounting/core.py')}}}
